name: Sync Wiki

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/wiki/**'
      - '.github/workflows/wiki-sync.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build wiki copy (strip .md for Wiki only)
        shell: bash
        run: |
          set -euo pipefail
          build_dir="_wikibuild"
          rm -rf "$build_dir"; mkdir -p "$build_dir"
          cp -R docs/wiki/. "$build_dir"/ || true
          [ -f "$build_dir/Home.md" ] || printf '# Home\n\n' > "$build_dir/Home.md"

          echo "== BEFORE rewrite =="
          grep -R --line-number -E '\]\([^)]+\.md(#[^)]*)?\)' "$build_dir" || true

          # Write small Python rewriter to a file (no heredoc!)
          py="$build_dir/_rewrite.py"
          printf '%s\n' \
"import pathlib, re, sys" \
"root = pathlib.Path(sys.argv[1])" \
"pat = re.compile(r'\\((?!https?://)([^)/\\s#?]+)\\.md(\\#[^)]+|\\))')" \
"for p in root.rglob(\"*.md\"): " \
"    s = p.read_text(encoding=\"utf-8\")" \
"    def repl(m):" \
"        # skip image links ![...](...)" \
"        before = s.rfind('![', 0, m.start())" \
"        if before != -1 and s.find('](', before) == m.start()-1:" \
"            return m.group(0)" \
"        return f'({m.group(1)}{m.group(2)}'" \
"    t = pat.sub(repl, s)" \
"    if t != s: p.write_text(t, encoding=\"utf-8\")" > \"$py\"

          python3 "$py" "$build_dir"

          echo "== AFTER rewrite =="
          grep -R --line-number -E '\]\([^)]+\.md(#[^)]*)?\)' "$build_dir" || true

      - name: Push to GitHub Wiki
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          cd _wikibuild
          git init
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No wiki updates."; exit 0
          fi
          git commit -m "Sync wiki from docs/wiki at $GITHUB_SHA"
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.wiki.git"
          git -c push.forceWithLease=false push --force --no-force-with-lease origin HEAD:main || \
          git -c push.forceWithLease=false push --force --no-force-with-lease origin HEAD:master
