name: Sync Wiki

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/wiki/**'
      - '.github/workflows/wiki-sync.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build wiki copy (strip .md only in copy)
        shell: bash
        run: |
          set -euo pipefail
          build_dir="_wikibuild"
          rm -rf "$build_dir"; mkdir -p "$build_dir"
          cp -R docs/wiki/. "$build_dir"/ || true
          [ -f "$build_dir/Home.md" ] || printf '# Home\n\n' > "$build_dir/Home.md"

          echo "== BEFORE =="
          grep -R --line-number -E '\]\([^)]+\.md(#[^)]*)?\)' "$build_dir" || true

          # Remove .md ONLY for local links (no scheme, no slash); keep ../README.md etc.
          find "$build_dir" -type f -name '*.md' -print0 | xargs -0 -I{} \
            perl -0777 -i -pe 's/\((?!https?:\/\/)([^)\/\s#?]+)\.md(\)|#[^)]+)\)/(\1\2/g' {}

          echo "== AFTER =="
          grep -R --line-number -E '\]\([^)]+\.md(#[^)]*)?\)' "$build_dir" || true

      - name: Push to GitHub Wiki
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          cd _wikibuild
          git init
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A

          if git diff --cached --quiet; then
            echo "No wiki updates."; exit 0
          fi

          git commit -m "Sync wiki from docs/wiki at $GITHUB_SHA"
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.wiki.git"
          git -c push.forceWithLease=false push --force --no-force-with-lease origin HEAD:main || \
          git -c push.forceWithLease=false push --force --no-force-with-lease origin HEAD:master
