name: Sync Wiki

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/wiki/**'
      - '.github/workflows/wiki-sync.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build wiki copy (strip .md in links for Wiki only)
        shell: bash
        run: |
          set -euo pipefail
          build_dir="_wikibuild"
          rm -rf "$build_dir"
          mkdir -p "$build_dir"
          cp -R docs/wiki/. "$build_dir"/ || true

          # Ensure Home.md exists
          if [ ! -f "$build_dir/Home.md" ]; then
            printf "# Home\n\n" > "$build_dir/Home.md"
          fi

          # Rewrite [Text](Page.md) -> [Text](Page) and anchors too
          # Only local links (no http/https), leave images alone.
          find "$build_dir" -type f -name '*.md' -print0 | xargs -0 -I{} \
            perl -0777 -pe 's/\((?!https?:\/\/)([^)#?]+)\.md(\)|#[^)]+)\)/(\1\2/g' -i {}

      - name: Push to GitHub Wiki
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          cd _wikibuild
          git init
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A

          # Idempotent: wenn nichts zu committen, sauber beenden
          if git diff --cached --quiet; then
            echo "No wiki updates."
            exit 0
          fi

          git commit -m "Sync wiki from docs/wiki at $GITHUB_SHA"
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.wiki.git"

          # Immer hart überschreiben (Lease-Override erzwingen)
          git -c push.forceWithLease=false push --force --no-force-with-lease origin HEAD:main || \
          git -c push.forceWithLease=false push --force --no-force-with-lease origin HEAD:master
